[2023-09-23T14:07:28.298+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: one_task_dag.one_task scheduled__2023-02-26T00:00:00+00:00 [queued]>
[2023-09-23T14:07:28.303+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: one_task_dag.one_task scheduled__2023-02-26T00:00:00+00:00 [queued]>
[2023-09-23T14:07:28.303+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-23T14:07:28.344+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): one_task> on 2023-02-26 00:00:00+00:00
[2023-09-23T14:07:28.345+0000] {standard_task_runner.py:57} INFO - Started process 19939 to run task
[2023-09-23T14:07:28.347+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'one_task_dag', 'one_task', 'scheduled__2023-02-26T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/one_task_dag.py', '--cfg-path', '/tmp/tmp_m7bsht0']
[2023-09-23T14:07:28.348+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask one_task
[2023-09-23T14:07:28.403+0000] {task_command.py:415} INFO - Running <TaskInstance: one_task_dag.one_task scheduled__2023-02-26T00:00:00+00:00 [running]> on host codespaces-4967f6
[2023-09-23T14:07:28.543+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='superman' AIRFLOW_CTX_DAG_ID='one_task_dag' AIRFLOW_CTX_TASK_ID='one_task' AIRFLOW_CTX_EXECUTION_DATE='2023-02-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-26T00:00:00+00:00'
[2023-09-23T14:07:28.544+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-23T14:07:28.544+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hello, this is a course exerices" > /workspaces/hands-on-introduction-data-engineering-4395021/lab/temp']
[2023-09-23T14:07:28.547+0000] {subprocess.py:86} INFO - Output:
[2023-09-23T14:07:28.548+0000] {subprocess.py:93} INFO - /usr/bin/bash: /workspaces/hands-on-introduction-data-engineering-4395021/lab/temp: Is a directory
[2023-09-23T14:07:28.548+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-23T14:07:28.552+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-23T14:07:28.554+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=one_task_dag, task_id=one_task, execution_date=20230226T000000, start_date=20230923T140728, end_date=20230923T140728
[2023-09-23T14:07:28.600+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 60 for task one_task (Bash command failed. The command returned a non-zero exit code 1.; 19939)
[2023-09-23T14:07:28.606+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-23T14:07:28.623+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
