[2023-09-23T14:05:27.237+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: one_task_dag.one_task manual__2023-09-23T14:05:21.247722+00:00 [queued]>
[2023-09-23T14:05:27.242+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: one_task_dag.one_task manual__2023-09-23T14:05:21.247722+00:00 [queued]>
[2023-09-23T14:05:27.242+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-23T14:05:27.301+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): one_task> on 2023-09-23 14:05:21.247722+00:00
[2023-09-23T14:05:27.303+0000] {standard_task_runner.py:57} INFO - Started process 18132 to run task
[2023-09-23T14:05:27.307+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'one_task_dag', 'one_task', 'manual__2023-09-23T14:05:21.247722+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/one_task_dag.py', '--cfg-path', '/tmp/tmp033hfefi']
[2023-09-23T14:05:27.307+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask one_task
[2023-09-23T14:05:27.360+0000] {task_command.py:415} INFO - Running <TaskInstance: one_task_dag.one_task manual__2023-09-23T14:05:21.247722+00:00 [running]> on host codespaces-4967f6
[2023-09-23T14:05:27.473+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='superman' AIRFLOW_CTX_DAG_ID='one_task_dag' AIRFLOW_CTX_TASK_ID='one_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-23T14:05:21.247722+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-23T14:05:21.247722+00:00'
[2023-09-23T14:05:27.474+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-23T14:05:27.474+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hello, this is a course exerices" > /workspaces/hands-on-introduction-data-engineering-4395021/lab/temp']
[2023-09-23T14:05:27.477+0000] {subprocess.py:86} INFO - Output:
[2023-09-23T14:05:27.478+0000] {subprocess.py:93} INFO - /usr/bin/bash: /workspaces/hands-on-introduction-data-engineering-4395021/lab/temp: Is a directory
[2023-09-23T14:05:27.478+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-23T14:05:27.482+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-23T14:05:27.483+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=one_task_dag, task_id=one_task, execution_date=20230923T140521, start_date=20230923T140527, end_date=20230923T140527
[2023-09-23T14:05:27.529+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task one_task (Bash command failed. The command returned a non-zero exit code 1.; 18132)
[2023-09-23T14:05:27.557+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-23T14:05:27.566+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
